//! Render a MusicXML part through the offline DOCUMENT path with a click
//! generated by the session-guide engine from THE SAME tempo map, so grid
//! alignment is audible: accented downbeats, quarter clicks, click panned
//! right. Writes the mix, the dry music, and the click alone.
//!
//! ```text
//! cargo run --release -p signal-orchestra --example render_with_click \
//!     [-- <score.mxl> [<part-substring> [<out-prefix>]]]
//! # defaults: Going Home fixture, "violin", listen/going_home_violin1
//! ```

use std::path::PathBuf;

use signal_orchestra::timing::{mix_click, render_click};
use signal_orchestra::{CSS_CONFIG, CSS_ROOT, load_strings, render_part_offline};
use signal_sampler::SamplerRig;
use signal_sampler::document::TempoPoint;

const ID: &str = "strings_1v";
const SR: u32 = 48_000;
const SEED: u64 = 0x60D0_1234_D0C5_EED0;

fn default_mxl() -> String {
    format!(
        "{}/../../../crates/keyflow/examples/mxl/GOING HOME - Dvorak New World Symphony 1.6 mxml.mxl",
        env!("CARGO_MANIFEST_DIR")
    )
}

fn write_wav(path: &std::path::Path, samples: &[f32]) -> eyre::Result<()> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)?;
    }
    let spec = hound::WavSpec {
        channels: 2,
        sample_rate: SR,
        bits_per_sample: 16,
        sample_format: hound::SampleFormat::Int,
    };
    let mut w = hound::WavWriter::create(path, spec)?;
    for &s in samples {
        w.write_sample((s.clamp(-1.0, 1.0) * 32767.0) as i16)?;
    }
    w.finalize()?;
    Ok(())
}

fn main() -> eyre::Result<()> {
    let mxl = std::env::args().nth(1).unwrap_or_else(default_mxl);
    let part_filter = std::env::args().nth(2).unwrap_or_else(|| "violin".into());
    let prefix = std::env::args()
        .nth(3)
        .unwrap_or_else(|| "listen/going_home_violin1".into());

    let sc = keyflow_orchestra::score::load(&mxl).map_err(|e| eyre::eyre!("score load: {e}"))?;
    let part = sc
        .parts
        .iter()
        .find(|p| p.name.to_lowercase().contains(&part_filter.to_lowercase()))
        .ok_or_else(|| eyre::eyre!("no part matching {part_filter:?}"))?;
    println!("part: {:?} ({} notes)", part.name, part.notes.len());

    let rig = SamplerRig::new_offline_with_cache_budget(SR, Some(8 * 1024 * 1024 * 1024));
    load_strings(&rig, ID, "1st Violins", "Mix", CSS_ROOT, CSS_CONFIG)
        .map_err(|e| eyre::eyre!(e))?;

    let res = render_part_offline(
        &rig,
        ID,
        part,
        &sc.meta.tempos,
        keyflow_orchestra::ProfileKind::Strings,
        SEED,
    )
    .map_err(|e| eyre::eyre!(e))?;
    println!(
        "rendered {:.1}s: {} notes, {} transitions, {} reactive fallbacks, {} markers",
        res.audio.len() as f64 / 2.0 / SR as f64,
        res.note_count,
        res.transitions.len(),
        res.reactive_fallbacks,
        res.markers.len()
    );
    // Deterministic arrival report against the score grid.
    let tempo: Vec<TempoPoint> = sc
        .meta
        .tempos
        .iter()
        .map(|t| TempoPoint { qn: t.qn, bpm: t.bpm })
        .collect();
    let mut worst = 0i64;
    for t in &res.transitions {
        // Nearest Arrival marker for this line/note.
        if let Some(m) = res
            .markers
            .iter()
            .filter(|m| {
                m.kind == signal_sampler::document::MarkerKind::Arrival
                    && m.note == t.to_note
                    && m.line == t.line
            })
            .min_by_key(|m| (m.frame as i64 - t.arrival as i64).abs())
        {
            worst = worst.max((t.arrival as i64 - m.frame as i64).abs());
        }
    }
    println!(
        "engine arrival vs schedule Arrival markers: worst {} frames ({:.2} ms)",
        worst,
        worst as f64 * 1000.0 / f64::from(SR)
    );
    let frames = res.audio.len() / 2;
    let click = render_click(&tempo, frames, SR, None);
    let mix = mix_click(&res.audio, &click, 0.5, 0.7);

    let prefix = PathBuf::from(prefix);
    let base = prefix
        .file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_else(|| "render".into());
    let dir = prefix.parent().unwrap_or(std::path::Path::new("."));
    write_wav(&dir.join(format!("{base}_click.wav")), &mix)?;
    write_wav(&dir.join(format!("{base}_dry.wav")), &res.audio)?;
    write_wav(&dir.join(format!("{base}_click_only.wav")), &click)?;
    println!(
        "wrote {base}_click.wav / {base}_dry.wav / {base}_click_only.wav in {}",
        dir.display()
    );
    Ok(())
}
