//! `engine_watch.rs` — the HTTP + SSE bridge for watchOS remotes.
//!
//! watchOS forbids WebSockets outside audio-streaming sessions (Apple
//! TN3135), so the watch cannot speak vox directly. This bridge exposes the
//! guitar rig's perform surface as plain JSON over URLSession-compatible
//! HTTP, mounted on the engine's existing axum app via
//! [`architect::host::EngineHost::extend`]:
//!
//! ```text
//! GET  /watch/v1/state          → WatchState snapshot (JSON)
//! GET  /watch/v1/events         → SSE stream of WatchState (on perf mutation)
//! POST /watch/v1/press/{index}  → Rig::press_stack(index)
//! POST /watch/v1/action/{name}  → tap-tempo / toggle-fx / toggle-boost /
//!                                 cycle-boost / toggle-tuner / next-song /
//!                                 prev-song
//! ```
//!
//! Internally the bridge is an ordinary vox client: it establishes
//! `RigClient` / `RigStreamClient` over an in-process
//! [`architect::LocalServer`] against the same `LayerRouter` every remote
//! uses — the core cannot tell a watch from a browser. The wire DTO
//! ([`WatchState`]) is a deliberately tiny projection of
//! [`PerformanceModel`]; its Swift mirror is generated by the
//! `gen_watch_swift` example so the Rust shape stays the source of truth.

use std::pin::Pin;
use std::task::{Context, Poll};

use architect::LocalServer;
use axum::extract::{Path, State};
use axum::http::StatusCode;
use axum::response::sse::{Event, KeepAlive, Sse};
use axum::routing::{get, post};
use axum::Router;
use signal_guitar_proto::rig::{RigClient, RigEvent, RigStreamClient};
use signal_guitar_proto::watch::WatchState;
use signal_guitar_proto::PerformanceModel;

/// Shared bridge state: one command client + the local server each SSE
/// subscriber establishes its own stream client from.
#[derive(Clone)]
struct Bridge {
    rig: RigClient,
    local: LocalServer,
}

/// Build the watch bridge router. Establishes the command client up front;
/// returns `None` (bridge disabled, engine unaffected) if that fails.
pub async fn router(local: LocalServer) -> Option<Router> {
    let rig: RigClient = match local.establish().await {
        Ok(c) => c,
        Err(e) => {
            tracing::warn!(error = %e, "watch bridge disabled: local rig client failed");
            return None;
        }
    };
    let bridge = Bridge { rig, local };
    Some(
        Router::new()
            .route("/watch/v1/state", get(state_snapshot))
            .route("/watch/v1/events", get(events))
            .route("/watch/v1/press/{index}", post(press))
            .route("/watch/v1/action/{name}", post(action))
            .with_state(bridge),
    )
}

/// Serialize a `WatchState` to its JSON wire form. Serialization of a
/// plain data struct can't realistically fail; degrade to `{}` with a log
/// rather than panicking the engine if it somehow does.
fn to_json(state: &WatchState) -> String {
    facet_json::to_string(state).unwrap_or_else(|e| {
        tracing::error!(error = %e, "watch state serialize failed");
        "{}".to_string()
    })
}

async fn state_snapshot(State(b): State<Bridge>) -> Result<String, StatusCode> {
    let perf = b.rig.perf().await.map_err(|e| {
        tracing::warn!(error = ?e, "watch /state: perf failed");
        StatusCode::BAD_GATEWAY
    })?;
    Ok(to_json(&WatchState::from(&perf)))
}

async fn press(State(b): State<Bridge>, Path(index): Path<u32>) -> Result<(), StatusCode> {
    b.rig.press_stack(index).await.map_err(|e| {
        tracing::warn!(error = ?e, index, "watch /press failed");
        StatusCode::BAD_GATEWAY
    })
}

async fn action(State(b): State<Bridge>, Path(name): Path<String>) -> Result<(), StatusCode> {
    let r = match name.as_str() {
        "tap-tempo" => b.rig.tap_tempo().await,
        "toggle-fx" => b.rig.toggle_fx().await,
        "toggle-boost" => b.rig.toggle_boost().await,
        "cycle-boost" => b.rig.cycle_boost().await,
        "toggle-tuner" => b.rig.toggle_tuner().await,
        "next-song" => b.rig.next_song().await,
        "prev-song" => b.rig.prev_song().await,
        _ => return Err(StatusCode::NOT_FOUND),
    };
    r.map_err(|e| {
        tracing::warn!(error = ?e, action = %name, "watch /action failed");
        StatusCode::BAD_GATEWAY
    })
}

/// SSE stream: an initial full snapshot, then a `WatchState` per perf
/// mutation. Meters/spectrum events are dropped here — the watch renders
/// scene state, not telemetry, and SSE over Bluetooth-relayed Wi-Fi wants
/// the thinnest possible stream.
async fn events(State(b): State<Bridge>) -> Result<axum::response::Response, StatusCode> {
    let stream_client: RigStreamClient = b.local.establish().await.map_err(|e| {
        tracing::warn!(error = %e, "watch /events: stream client failed");
        StatusCode::BAD_GATEWAY
    })?;

    let (out_tx, out_rx) = tokio::sync::mpsc::channel::<String>(8);

    // Initial snapshot so a (re)connecting watch is correct immediately.
    if let Ok(perf) = b.rig.perf().await {
        let _ = out_tx.send(to_json(&WatchState::from(&perf))).await;
    }

    tokio::spawn(async move {
        let (tx, mut rx) = vox::channel::<RigEvent>();
        let call = stream_client.events(tx);
        let pump = async {
            while let Ok(Some(event)) = rx.recv().await {
                // SelfRef events lend their value; clone out the perf.
                let mut perf: Option<PerformanceModel> = None;
                let _ = event.map(|ev| {
                    if let RigEvent::Perf(p) = ev {
                        perf = Some(p.clone());
                    }
                });
                if let Some(p) = perf
                    && out_tx.send(to_json(&WatchState::from(&p))).await.is_err()
                {
                    break; // SSE client gone
                }
            }
        };
        // The subscribe call resolving means the subscription ended.
        tokio::select! {
            _ = pump => {}
            _ = call => {}
        }
    });

    use axum::response::IntoResponse as _;
    Ok(Sse::new(SseStream(out_rx))
        .keep_alive(KeepAlive::default())
        .into_response())
}

/// A `Stream` over the bridge's mpsc receiver — avoids pulling a
/// tokio-stream dep for one adapter. Shared with the session half of the
/// bridge (`engine_watch_session.rs`).
pub(crate) struct SseStream(pub(crate) tokio::sync::mpsc::Receiver<String>);

impl futures_util::Stream for SseStream {
    type Item = Result<Event, std::convert::Infallible>;

    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        self.0
            .poll_recv(cx)
            .map(|opt| opt.map(|json| Ok(Event::default().data(json))))
    }
}
