[package]
name = "fasttrackstudio-desktop"
version = "0.1.0"
authors = ["Cody Wright <acodywright@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { workspace = true, features = ["desktop"] }
keyflow-ui = { workspace = true, default-features = false, features = ["web"] }
rfd = "0.15"
tokio = { workspace = true, features = ["full"] }
zip = "2"

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = []
mobile = ["dioxus/mobile"]
