[application]

[web.app]

# HTML title tag content
title = "desktop"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.fasttrackstudio.fasttrackstudio"
publisher = "FastTrack Studio"
icon = ["./assets/favicon.ico"]

[bundle.macos]
minimum_system_version = "13.0"
