#!/usr/bin/env python3
"""Inject NKI loop points into a Cinematic Studio per-section library.styx.

The CS extraction's `_patches/<Section>/library.styx` specs were generated by
nki-styx + later measurement passes (arrival_ms), but only 1st Violins got
loop points. Regenerating whole specs would lose arrival_ms, so this script
does the minimal thing: map each looped NKI zone to its extracted WAV path
(same formula as nki-styx) and splice `loop_start`/`loop_end` into the
existing spec's zone blocks, touching nothing else.

Usage:
  inject_cs_loops.py <zones.tsv> "<Section Label>" <library.styx> [--check] [--write]

  --check  compare mapped loops against loops already in the spec (validation
           on 1st Violins, whose loops are ground truth)
  --write  rewrite the spec in place (a .bak sibling is written first)

zones.tsv comes from the `nki` decoder (kontakt-extract skill):
  nki "<Instrument>.nki" --jdx … --hu … --snpid … --zones --out-dir …
For CSS Cellos use the "Classic Legato Patches" NKI — the main Cellos NKI has
an FNTableImpl v3 monolith filename table the decoder can't name yet; the
Classic variant carries the identical 50,305-zone table with v2 names.
"""

import sys
from pathlib import Path

# nki-styx's CSS articulation -> category folder taxonomy (+ the "Pizz" token
# the non-1st-Violins sections use for Pizzicato).
CATEGORY = {}
for arts, cat in [
    (("Nonvib", "Vibsus"), "Sustain"),
    (("Leg", "Legzero", "NVLeg", "NVLegzero"), "Legato"),
    (("Marcato", "Sfz", "Spiccato", "Staccatissimo", "Staccato"), "Short"),
    (("Bartokpizz", "Pizzicato", "Pizz"), "Pizzicato"),
    (("Clegno", "Harm", "HTrills", "Port", "Tremolo", "WTrills"), "Special"),
    (("Harmrel", "HTrel", "Marcrel", "NVrel", "Tremrel", "Vsusrel", "WTrel"), "Releases"),
]:
    for a in arts:
        CATEGORY[a] = cat


def load_loop_map(tsv_path: Path, section_label: str) -> dict[str, tuple[int, int]]:
    """wav-relative-path -> (loop_start, loop_end) for looped zones only."""
    loops: dict[str, tuple[int, int]] = {}
    conflicts = 0
    with open(tsv_path) as fh:
        header = fh.readline().rstrip("\n").split("\t")
        col = {name: i for i, name in enumerate(header)}
        for line in fh:
            f = line.rstrip("\n").split("\t")
            ls, le = int(f[col["loop_start"]]), int(f[col["loop_end"]])
            if le <= ls or le <= 0:
                continue
            sample = f[col["sample"]]
            base = sample.rsplit("/", 1)[-1]
            stem = base.removesuffix(".ncw").removesuffix(".wav")
            parts = stem.split("_")
            if len(parts) < 4:
                continue
            _sec, artic, mic = parts[0], parts[1], parts[2]
            cat = CATEGORY.get(artic)
            if cat is None:
                print(f"  WARNING: looped zone with unmapped articulation {artic!r}: {base}")
                continue
            rest = "_".join(parts[3:])
            wav = f"{mic}/{section_label}/{cat}/{artic}/{rest}.wav"
            prev = loops.get(wav)
            if prev is not None:
                if prev != (ls, le):
                    conflicts += 1
                continue  # first-wins — matches nki-styx's accumulation order
            loops[wav] = (ls, le)
    if conflicts:
        print(f"  NOTE: {conflicts} file(s) had differing loops across zones (first wins)")
    return loops


def main() -> None:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    flags = {a for a in sys.argv[1:] if a.startswith("--")}
    if len(args) != 3:
        sys.exit(__doc__)
    tsv_path, section_label, styx_path = Path(args[0]), args[1], Path(args[2])
    check, write = "--check" in flags, "--write" in flags

    loops = load_loop_map(tsv_path, section_label)
    print(f"{section_label}: {len(loops)} looped file(s) mapped from {tsv_path.name}")

    text = styx_path.read_text()
    out_lines: list[str] = []
    block: list[str] = []
    in_zone = False
    stats = {"injected": 0, "already": 0, "match": 0, "mismatch": 0, "no_wav_zone_looped": 0}
    unmatched = dict(loops)  # loops whose wav path never appears in the spec

    for line in text.splitlines(keepends=True):
        stripped = line.strip()
        if not in_zone:
            out_lines.append(line)
            if stripped == "{":
                in_zone = True
                block = [out_lines.pop()]
            continue
        block.append(line)
        if stripped != "}":
            continue
        # end of zone block — process
        in_zone = False
        file_val = None
        has_loop = None
        for bl in block:
            s = bl.strip()
            if s.startswith("file "):
                file_val = s.split(None, 1)[1].strip().strip('"')
            elif s.startswith("loop_start "):
                has_loop = int(s.split()[1])
        mapped = loops.get(file_val) if file_val else None
        if mapped is not None and file_val is not None:
            unmatched.pop(file_val, None)
        if mapped is not None and has_loop is not None:
            stats["already"] += 1
            if check:
                le_existing = None
                for bl in block:
                    s = bl.strip()
                    if s.startswith("loop_end "):
                        le_existing = int(s.split()[1])
                if (has_loop, le_existing) == mapped:
                    stats["match"] += 1
                else:
                    stats["mismatch"] += 1
                    print(f"  MISMATCH {file_val}: spec ({has_loop}, {le_existing}) vs nki {mapped}")
        elif mapped is not None:
            ls, le = mapped
            indent = block[1][: len(block[1]) - len(block[1].lstrip())] if len(block) > 1 else "        "
            close = block.pop()
            block.append(f"{indent}{'loop_start':<12} {ls}\n")
            block.append(f"{indent}{'loop_end':<12} {le}\n")
            block.append(close)
            stats["injected"] += 1
        out_lines.extend(block)

    print(f"  injected={stats['injected']} already={stats['already']}", end="")
    if check:
        print(f" match={stats['match']} mismatch={stats['mismatch']}", end="")
    print(f" loops-without-spec-zone={len(unmatched)}")
    for wav in list(unmatched)[:5]:
        print(f"    e.g. no spec zone for looped {wav}")

    if write and stats["injected"]:
        bak = styx_path.with_suffix(".styx.bak")
        bak.write_text(text)
        styx_path.write_text("".join(out_lines))
        print(f"  wrote {styx_path} (backup at {bak.name})")
    elif write:
        print("  nothing to inject; spec unchanged")


if __name__ == "__main__":
    main()
